"""
Velox - Configuration & Settings
All settings loaded from .env with sensible defaults.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load .env from project root
_project_root = Path(__file__).resolve().parent.parent
load_dotenv(_project_root / ".env", override=True)


def _env(key: str, default: str = "") -> str:
    return os.getenv(key, default)


def _env_float(key: str, default: float = 0.0) -> float:
    return float(os.getenv(key, str(default)))


def _env_int(key: str, default: int = 0) -> int:
    return int(os.getenv(key, str(default)))


# ── API Keys ──────────────────────────────────────────────────────
ANTHROPIC_API_KEY = _env("ANTHROPIC_API_KEY")
OPENAI_API_KEY = _env("OPENAI_API_KEY")
PERPLEXITY_API_KEY = _env("PERPLEXITY_API_KEY")

# Twitter / X
X_BEARER_TOKEN = _env("X_BEARER_TOKEN")
X_CONSUMER_KEY = _env("X_CONSUMER_KEY")
X_CONSUMER_SECRET = _env("X_CONSUMER_SECRET")

# Alpaca
ALPACA_API_KEY = _env("ALPACA_API_KEY")
ALPACA_SECRET_KEY = _env("ALPACA_SECRET_KEY")
ALPACA_PAPER = _env("ALPACA_PAPER", "true").lower() in ("true", "1", "yes")
PAPER_MODE = _env("PAPER_MODE", "true" if ALPACA_PAPER else "false").lower() in ("true", "1", "yes")

# Polygon
POLYGON_API_KEY = _env("POLYGON_API_KEY")
UW_API_TOKEN = _env("UW_API_TOKEN")
UW_STREAM_MODE = _env("UW_STREAM_MODE", "auto").lower()
UW_STREAM_URL = _env("UW_STREAM_URL", "wss://api.unusualwhales.com/socket")
UW_STREAM_STALE_SECONDS = _env_int("UW_STREAM_STALE_SECONDS", 90)
UW_STREAM_BASE_BACKOFF_SECONDS = _env_float("UW_STREAM_BASE_BACKOFF_SECONDS", 5.0)
UW_STREAM_MAX_BACKOFF_SECONDS = _env_float("UW_STREAM_MAX_BACKOFF_SECONDS", 120.0)
UW_STREAM_SIGNAL_WINDOW_SECONDS = _env_int("UW_STREAM_SIGNAL_WINDOW_SECONDS", 300)
UW_STREAM_MIN_FLOW_PREMIUM = _env_float("UW_STREAM_MIN_FLOW_PREMIUM", 100000.0)
UW_STREAM_MIN_DARK_POOL_PREMIUM = _env_float("UW_STREAM_MIN_DARK_POOL_PREMIUM", 250000.0)
UW_STREAM_LOG_RAW = _env("UW_STREAM_LOG_RAW", "false").lower() in ("true", "1", "yes")
FRED_API_KEY = _env("FRED_API_KEY")
FINNHUB_API_KEY = _env("FINNHUB_API_KEY")
ALPHA_VANTAGE_API_KEY = _env("ALPHA_VANTAGE_API_KEY")

# ── Trading Parameters ────────────────────────────────────────────
TOTAL_CAPITAL = _env_float("TOTAL_CAPITAL", 25000)
DEPLOYED_CAPITAL = _env_float("DEPLOYED_CAPITAL", 25000)
POSITION_SIZE_PCT = _env_float("POSITION_SIZE_PCT", 2.0)
MAX_CONCURRENT_POSITIONS = _env_int("MAX_CONCURRENT_POSITIONS", 5)
MAX_DAILY_LOSS_PCT = _env_float("MAX_DAILY_LOSS_PCT", 3.0)
MAX_POSITION_LOSS_PCT = _env_float("MAX_POSITION_LOSS_PCT", 1.0)
TAKE_PROFIT_1_PCT = _env_float("TAKE_PROFIT_1_PCT", 1.5)
TAKE_PROFIT_2_PCT = _env_float("TAKE_PROFIT_2_PCT", 2.5)
TRAILING_STOP_PCT = _env_float("TRAILING_STOP_PCT", 0.5)
STOP_LOSS_PCT = _env_float("STOP_LOSS_PCT", 1.0)
MAX_HOLD_HOURS = _env_float("MAX_HOLD_HOURS", 4)
EOD_EXIT_TIME = _env("EOD_EXIT_TIME", "15:30")  # ET

# ── Scanner Parameters ────────────────────────────────────────────
MIN_PRICE = _env_float("MIN_PRICE", 5.0)
MAX_PRICE = _env_float("MAX_PRICE", 500.0)
MIN_VOLUME = _env_int("MIN_VOLUME", 1_000_000)
VOLUME_SPIKE_MULTIPLIER = _env_float("VOLUME_SPIKE_MULTIPLIER", 2.0)
MIN_MOMENTUM_PCT = _env_float("MIN_MOMENTUM_PCT", 2.0)
SCAN_INTERVAL_SECONDS = _env_int("SCAN_INTERVAL_SECONDS", 300)
SCAN_INTERVAL_FAST_SECONDS = _env_int("SCAN_INTERVAL_FAST_SECONDS", 60)
SCAN_INTERVAL_SLOW_SECONDS = _env_int("SCAN_INTERVAL_SLOW_SECONDS", 300)
SCAN_INTERVAL_EXTENDED_SECONDS = _env_int("SCAN_INTERVAL_EXTENDED_SECONDS", 300)
SCAN_INTERVAL_OVERNIGHT_SECONDS = _env_int("SCAN_INTERVAL_OVERNIGHT_SECONDS", 600)
SCAN_REGIME_HYSTERESIS_WINDOW = _env_int("SCAN_REGIME_HYSTERESIS_WINDOW", 3)
SCAN_REGIME_MIN_CONFIRMATIONS = _env_int("SCAN_REGIME_MIN_CONFIRMATIONS", 2)
SCANNER_TECHNICAL_FETCH_DELAY_SECONDS = _env_float("SCANNER_TECHNICAL_FETCH_DELAY_SECONDS", 0.26)
SCANNER_SIGNAL_FIRST_SEEN_TTL_SECONDS = _env_int("SCANNER_SIGNAL_FIRST_SEEN_TTL_SECONDS", 3600)
FAST_PATH_ENABLED = _env("FAST_PATH_ENABLED", "true").lower() in ("true", "1", "yes")
FAST_PATH_MIN_CHANGE_PCT = _env_float("FAST_PATH_MIN_CHANGE_PCT", 5.0)
FAST_PATH_MIN_VOLUME_SPIKE = _env_float("FAST_PATH_MIN_VOLUME_SPIKE", 2.0)
FAST_PATH_SIZE_MULTIPLIER = _env_float("FAST_PATH_SIZE_MULTIPLIER", 0.4)
FAST_PATH_RSI_MIN = _env_float("FAST_PATH_RSI_MIN", 40.0)
FAST_PATH_RSI_MAX = _env_float("FAST_PATH_RSI_MAX", 85.0)
FAST_PATH_EVAL_MAX_CYCLES = _env_int("FAST_PATH_EVAL_MAX_CYCLES", 6)
FAST_PATH_EVAL_MAX_AGE_SECONDS = _env_int("FAST_PATH_EVAL_MAX_AGE_SECONDS", 90)
SWING_MODE_TRAIL_PCT = _env_float("SWING_MODE_TRAIL_PCT", 4.5)
SWING_MODE_SIZE_REDUCTION = _env_float("SWING_MODE_SIZE_REDUCTION", 0.7)
SWING_MODE_DISABLE_FAST_PATH = _env("SWING_MODE_DISABLE_FAST_PATH", "true").lower() in ("true", "1", "yes")
COPY_TRADER_MODE = _env("COPY_TRADER_MODE", "auto").lower()
COPY_TRADER_SIGNAL_WINDOW_SECONDS = _env_int("COPY_TRADER_SIGNAL_WINDOW_SECONDS", 900)
COPY_TRADER_STREAM_STALE_SECONDS = _env_int("COPY_TRADER_STREAM_STALE_SECONDS", 180)
COPY_TRADER_STREAM_RULE_REFRESH_SECONDS = _env_int("COPY_TRADER_STREAM_RULE_REFRESH_SECONDS", 3600)
COPY_TRADER_STREAM_BASE_BACKOFF_SECONDS = _env_float("COPY_TRADER_STREAM_BASE_BACKOFF_SECONDS", 5.0)
COPY_TRADER_STREAM_MAX_BACKOFF_SECONDS = _env_float("COPY_TRADER_STREAM_MAX_BACKOFF_SECONDS", 300.0)
COPY_TRADER_STREAM_429_COOLDOWN_SECONDS = _env_float("COPY_TRADER_STREAM_429_COOLDOWN_SECONDS", 300.0)
COPY_TRADER_EXIT_TIGHTEN_MULT = _env_float("COPY_TRADER_EXIT_TIGHTEN_MULT", 0.6)
COPY_TRADER_EXIT_MIN_TRAIL_PCT = _env_float("COPY_TRADER_EXIT_MIN_TRAIL_PCT", 1.5)
COPY_TRADER_STRONG_EXIT_MIN_SIGNALS = _env_int("COPY_TRADER_STRONG_EXIT_MIN_SIGNALS", 2)
COPY_TRADER_AUTO_EXIT_STRONG = _env("COPY_TRADER_AUTO_EXIT_STRONG", "false").lower() in ("true", "1", "yes")

# ── Sentiment Parameters ──────────────────────────────────────────
MIN_ENTRY_SENTIMENT = _env_float("MIN_ENTRY_SENTIMENT", 0.3)
EXIT_SENTIMENT_WARNING = _env_float("EXIT_SENTIMENT_WARNING", 0.3)
EXIT_SENTIMENT_CRITICAL = _env_float("EXIT_SENTIMENT_CRITICAL", 0.0)

# ── Dashboard ─────────────────────────────────────────────────────
DASHBOARD_HOST = _env("DASHBOARD_HOST", "0.0.0.0")
DASHBOARD_PORT = _env_int("DASHBOARD_PORT", 8421)
DASHBOARD_TOKEN = _env("DASHBOARD_TOKEN", "")
DASHBOARD_START_RETRIES = _env_int("DASHBOARD_START_RETRIES", 15)
DASHBOARD_START_RETRY_SECONDS = _env_float("DASHBOARD_START_RETRY_SECONDS", 1.0)

# ── Logging ───────────────────────────────────────────────────────
LOG_LEVEL = _env("LOG_LEVEL", "INFO")

# ── Risk Management (Advanced) ────────────────────────────────────
ATR_PERIOD = _env_int("ATR_PERIOD", 14)
ATR_STOP_MULTIPLIER = _env_float("ATR_STOP_MULTIPLIER", 1.5)
ATR_TRAIL_MULTIPLIER = _env_float("ATR_TRAIL_MULTIPLIER", 2.0)
WEEKLY_MAX_LOSS_PCT = _env_float("WEEKLY_MAX_LOSS_PCT", 5.0)
EXTENDED_HOURS_SIZE_MULT = _env_float("EXTENDED_HOURS_SIZE_MULT", 0.5)
MAX_PRICE_CHASE_PCT = _env_float("MAX_PRICE_CHASE_PCT", 0.5)
CASH_ACCOUNT = _env("CASH_ACCOUNT", "true").lower() in ("true", "1", "yes")
MAX_SECTOR_PCT = _env_float("MAX_SECTOR_PCT", 40.0)

# ── Consensus Engine ──────────────────────────────────────────────
CONSENSUS_ENABLED = _env("CONSENSUS_ENABLED", "true").lower() in ("true", "1", "yes")
CONSENSUS_MIN_CONFIDENCE = _env_int("CONSENSUS_MIN_CONFIDENCE", 70)
CONSENSUS_CACHE_SECONDS = _env_int("CONSENSUS_CACHE_SECONDS", 300)
CONSENSUS_MAX_CALLS_PER_HOUR = _env_int("CONSENSUS_MAX_CALLS_PER_HOUR", 60)
OPENAI_MODEL = _env("OPENAI_MODEL", "gpt-5.4")
CLAUDE_MODEL = _env("CLAUDE_MODEL", "claude-sonnet-4-5-20250929")
XAI_API_KEY = _env("XAI_API_KEY", "")
XAI_MODEL = _env("XAI_MODEL", "grok-4-fast-reasoning")
PERPLEXITY_MODEL = _env("PERPLEXITY_MODEL", "sonar-pro")
JURY_RETRO_ENABLED = _env("JURY_RETRO_ENABLED", "true").lower() in ("true", "1", "yes")
JURY_RETRO_LOOKBACK_TRADES = _env_int("JURY_RETRO_LOOKBACK_TRADES", 40)
JURY_RETRO_MIN_MATCHES = _env_int("JURY_RETRO_MIN_MATCHES", 3)
OPENAI_INPUT_COST_PER_MTOK = _env_float("OPENAI_INPUT_COST_PER_MTOK", 2.5)
OPENAI_OUTPUT_COST_PER_MTOK = _env_float("OPENAI_OUTPUT_COST_PER_MTOK", 15.0)
CLAUDE_INPUT_COST_PER_MTOK = _env_float("CLAUDE_INPUT_COST_PER_MTOK", 3.0)
CLAUDE_OUTPUT_COST_PER_MTOK = _env_float("CLAUDE_OUTPUT_COST_PER_MTOK", 15.0)
XAI_INPUT_COST_PER_MTOK = _env_float("XAI_INPUT_COST_PER_MTOK", 0.2)
XAI_OUTPUT_COST_PER_MTOK = _env_float("XAI_OUTPUT_COST_PER_MTOK", 0.5)
PERPLEXITY_INPUT_COST_PER_MTOK = _env_float("PERPLEXITY_INPUT_COST_PER_MTOK", 3.0)
PERPLEXITY_OUTPUT_COST_PER_MTOK = _env_float("PERPLEXITY_OUTPUT_COST_PER_MTOK", 15.0)
PERPLEXITY_REQUEST_COST_USD = _env_float("PERPLEXITY_REQUEST_COST_USD", 0.006)

# ── Entry Controls ────────────────────────────────────────────────
MIN_JURY_CONFIDENCE = _env_int("MIN_JURY_CONFIDENCE", 40)
MIN_NOTIONAL = _env_float("MIN_NOTIONAL", 25.0)
REENTRY_COOLDOWN_SECONDS = _env_int("REENTRY_COOLDOWN_SECONDS", 300)
BLACKLIST_DURATION_SECONDS = _env_int("BLACKLIST_DURATION_SECONDS", 86400)
MAX_ENTRIES_PER_SYMBOL_PER_DAY = _env_int("MAX_ENTRIES_PER_SYMBOL_PER_DAY", 2)
MAX_ENTRIES_PER_STRATEGY_PER_DAY = _env_int("MAX_ENTRIES_PER_STRATEGY_PER_DAY", 8)

# ── Payload Capture (paper trading diagnostics) ───────────────────
CAPTURE_ALPACA_PAYLOADS = _env("CAPTURE_ALPACA_PAYLOADS", "false").lower() in ("true", "1", "yes")
MARKET_STREAM_AUTH_LIMIT_RETRY_SECONDS = _env_float("MARKET_STREAM_AUTH_LIMIT_RETRY_SECONDS", 5.0)

# ── Notifications ─────────────────────────────────────────────────
SLACK_WEBHOOK_URL = _env("SLACK_WEBHOOK_URL", "")

# Options Trading
OPTIONS_ENABLED = _env("OPTIONS_ENABLED", "false").lower() in ("true", "1", "yes")
OPTIONS_ALLOCATION_PCT = float(_env("OPTIONS_ALLOCATION_PCT", "50"))  # % of position size to allocate to options
OPTIONS_MONITOR_INTERVAL_SECONDS = _env_int("OPTIONS_MONITOR_INTERVAL_SECONDS", 30)
OPTIONS_CONTRACT_DTE_MIN = _env_int("OPTIONS_CONTRACT_DTE_MIN", 7)
OPTIONS_CONTRACT_DTE_MAX = _env_int("OPTIONS_CONTRACT_DTE_MAX", 21)
OPTIONS_TARGET_DTE = _env_int("OPTIONS_TARGET_DTE", 12)
OPTIONS_TARGET_DELTA = _env_float("OPTIONS_TARGET_DELTA", 0.40)
OPTIONS_MIN_OPEN_INTEREST = _env_int("OPTIONS_MIN_OPEN_INTEREST", 10)
OPTIONS_PREMIUM_TRAIL_PCT = _env_float("OPTIONS_PREMIUM_TRAIL_PCT", 35.0)
OPTIONS_PREMIUM_TIGHT_TRAIL_PCT = _env_float("OPTIONS_PREMIUM_TIGHT_TRAIL_PCT", 20.0)
OPTIONS_PREMIUM_STOP_LOSS_PCT = _env_float("OPTIONS_PREMIUM_STOP_LOSS_PCT", 50.0)
OPTIONS_PREMIUM_PROFIT_TARGET_PCT = _env_float("OPTIONS_PREMIUM_PROFIT_TARGET_PCT", 100.0)
OPTIONS_PREMIUM_TRIPLE_TARGET_MULT = _env_float("OPTIONS_PREMIUM_TRIPLE_TARGET_MULT", 3.0)
OPTIONS_MIN_DAYS_TO_EXPIRY = _env_int("OPTIONS_MIN_DAYS_TO_EXPIRY", 2)
OPTIONS_MAX_PORTFOLIO_PCT = _env_float("OPTIONS_MAX_PORTFOLIO_PCT", 10.0)
OPTIONS_EXIT_BID_AWARE_LIMIT = _env("OPTIONS_EXIT_BID_AWARE_LIMIT", "true").lower() in ("true", "1", "yes")
OPTIONS_EXIT_BID_DISCOUNT_PCT = _env_float("OPTIONS_EXIT_BID_DISCOUNT_PCT", 0.25)
OPTIONS_EXIT_MID_DISCOUNT_PCT = _env_float("OPTIONS_EXIT_MID_DISCOUNT_PCT", 2.0)
OPTIONS_EXIT_MARKET_FALLBACK = _env("OPTIONS_EXIT_MARKET_FALLBACK", "true").lower() in ("true", "1", "yes")
